FROM docker.smilecdr.com/smilecdr:2021.11.R02

WORKDIR /home/smile/smilecdr

copy ./cdr-config-Master-modified.properties ./classes/cdr-config-Master.properties
copy ./interceptors/target/interceptors-1.0-SNAPSHOT.jar ./customerlib/
